

#include "nsISupports.idl"
#include "domstubs.idl"

/**
 *
 */
[scriptable, uuid(0adb1d92-8131-4bcd-b216-ec8246b7e0a4)]
interface diIAttrChangedTxn: nsISupports
{


  nsISupports getNode();
  wstring getAttributeName();
  wstring getOldData();
  wstring getNewData();
};

