  <html:script src="chrome://inspector/content/hooks.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diInnerHtmlChangedTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diNodeInsertionTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diNodeDeletionTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diStyleAttrChangeTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diCommentOrPIChangeTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diRemoveAttributeNSTxn.js"></html:script>
  <html:script src="chrome://bluegriffon/content/txns/diSetAttributeNSTxn.js"></html:script>

  <html:script src="chrome://bluegriffon/content/utils/dgid.js"></html:script>
  <html:script src="chrome://bluegriffon/content/utils/global.js"></html:script>
  <html:script src="chrome://bluegriffon/content/utils/notifiers.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/bg-command-controller.js"></html:script>

  <!-- Custom Elements (XBL replacement) -->
  <html:script src="chrome://bluegriffon/content/js/structurebar-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/tabeditor-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/tab-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/filepickerbutton-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/floatingpanel-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/deckedPanelsTabs-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/rulers-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/rotator-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/multistate-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/lengthbox-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/ecolorpicker-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/cssClassPicker-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/menulist-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/media-element.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/commands.js"></html:script>
  <html:script src="chrome://aria/content/aria-roles.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/bluegriffon.js"></html:script>
  <html:script src="chrome://global/content/globalOverlay.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/colourPickerHelper.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/zoomManager.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/recentPages.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/toolbars.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/languages.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/recentPages.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/updateManager.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/rotate.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/html5.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/tableResizer.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/beautify-html.js"></html:script>
  <html:script src="chrome://bluegriffon/content/js/rebuildTOC.js"></html:script>
  <html:script src="resource://gre/res/codemirror/themes-list.js"></html:script>

  <html:script src="chrome://bluegriffon/content/js/responsive.js"></html:script>
