  <script type="application/x-javascript" src="chrome://inspector/content/hooks.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diInnerHtmlChangedTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diNodeInsertionTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diNodeDeletionTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diStyleAttrChangeTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diCommentOrPIChangeTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diRemoveAttributeNSTxn.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/txns/diSetAttributeNSTxn.js"/>

  <script type="application/javascript" src="chrome://bluegriffon/content/utils/dgid.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/global.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/utils/notifiers.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/bg-command-controller.js"/>

  <!-- Custom Elements (XBL replacement) -->
  <script type="application/javascript" src="chrome://bluegriffon/content/js/structurebar-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/tabeditor-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/tab-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/filepickerbutton-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/floatingpanel-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/deckedPanelsTabs-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/rulers-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/rotator-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/multistate-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/lengthbox-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/ecolorpicker-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/cssClassPicker-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/menulist-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/media-element.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/commands.js"/>
  <script type="application/javascript" src="chrome://aria/content/aria-roles.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/bluegriffon.js"/>
  <script type="application/javascript" src="chrome://global/content/globalOverlay.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/colourPickerHelper.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/zoomManager.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/recentPages.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/toolbars.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/languages.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/recentPages.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/updateManager.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/rotate.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/html5.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/tableResizer.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/beautify-html.js"/>
  <script type="application/javascript" src="chrome://bluegriffon/content/js/rebuildTOC.js"/>
  <script type="application/javascript" src="resource://gre/res/codemirror/themes-list.js"/>

  <script type="application/javascript" src="chrome://bluegriffon/content/js/responsive.js"/>
